version: '3.7' 

services:

    mielentila_backend:
      image: ohtuprothl/staging_test:latest
      restart: unless-stopped
      container_name: mielentila_backend
      ports:
        - 3001:3001

networks:
  default:
    external:
      name: ohtup
